### ISSUE TITLE
hz_linesearch! fails to converge

### ISSUE THREAD

**Issue by Ken-B** [JuliaOpt/Optim.jl#240] opened 2016-07-05 23:36 UTC
In my package [MinFinder](https://github.com/Ken-B/MinFinder.jl) I use `Fminbox` to generate many local searches. Starting with `Optim` to v0.5.0 I notice a problem with `hz_linesearch!` on the Rastrigin test function:

```julia
julia> using Optim
#suppressed many warnings

julia> rastrigin_f(x) = x[1]^2 + x[2]^2 - cos(18x[1]) - cos(18x[2])
rastrigin_f (generic function with 1 method)

julia> function rastrigin_g!(x, g)
           g[1] = 2x[1] +18sin(18x[1])
           g[2] = 2x[2] +18sin(18x[2])
           return nothing
       end
rastrigin_g! (generic function with 1 method)

julia> df = DifferentiableFunction(rastrigin_f, rastrigin_g!)
Optim.DifferentiableFunction(rastrigin_f,rastrigin_g!,fg!)

julia> optimize(df, rand(2)) #this works
Results of Optimization Algorithm
 * Algorithm: L-BFGS
 * Starting Point: [0.20289413464666772,0.06818434139917184]
 * Minimizer: [0.34692381469254663,0.34692381468112554]
 * Minimum: -1.757801e+00
 * Iterations: 8
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 45
 * Gradient Calls: 45

julia> optimize(df, rand(2), [-1.0, -1.0], [1.0, 1.0], Fminbox()) # works most of the time
WARNING: could not attach metadata for @simd loop.
Results of Optimization Algorithm
 * Algorithm: Fminbox with Conjugate Gradient
 * Starting Point: [0.9016298331952515,0.198706763888576]
 * Minimizer: [0.9999999999999004,0.34692381472045547]
 * Minimum: -5.392174e-01
 * Iterations: 4
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 237
 * Gradient Calls: 181

julia> using MinFinder

julia> optimize(df, [-1.0, -1.0], [1.0, 1.0], Fminfinder()) #fails most of the time
ERROR: Linesearch failed to converge
 in hz_linesearch! at /Users/ken/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:362
 in hz_linesearch! at /Users/ken/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:176 (repeats 10 times)
 in optimize at /Users/ken/.julia/v0.4/Optim/src/cg.jl:202
 in optimize at /Users/ken/.julia/v0.4/Optim/src/fminbox.jl:200
 in optimize at /Users/ken/.julia/v0.4/MinFinder/src/minfinder_main.jl:180

julia> optimize(df, [0.6319212216798746,-0.9994104395969008], [-1.0, -1.0], [1.0, 1.0], Fminbox())
ERROR: Linesearch failed to converge #failure example
 in hz_linesearch! at /Users/ken/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:362
 in hz_linesearch! at /Users/ken/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:176 (repeats 10 times)
 in optimize at /Users/ken/.julia/v0.4/Optim/src/cg.jl:202
 in optimize at /Users/ken/.julia/v0.4/Optim/src/fminbox.jl:200

julia> optimize(df, [0.6319212216798746,-0.9994104395969008], [-1.0, -1.0], [1.0, 1.0], Fminbox(); 
linesearch! = Optim.backtracking_linesearch!) #works with another linesearch! function
Results of Optimization Algorithm
 * Algorithm: Fminbox with Conjugate Gradient
 * Starting Point: [0.6319212216798746,-0.9994104395969008]
 * Minimizer: [0.6938444561552295,-0.9999999999999986]
 * Minimum: -1.759204e-01
 * Iterations: 4
 * Convergence: true
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: true
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 741
 * Gradient Calls: 170
```

I just tried and haven't seen it fail on the `teh/constrained branch`. 

Just I not use the `hz_linesearch!` by default?

I would have reported earlier but somehow my local Optim got stuck at v0.4.5. Let me know what I can do to fix. 
Thank you.

**Comment by pkofod** [comment] 2016-07-06 06:42
That's annoying. There should be no worsening of hz line search, so no, I wouldn't advise you to use backtracking.

You say you suppress dep. warnings. Is this only on v0.5 of Julia? Also, what combination of packages (MinFinder and Optim) works?

**Comment by multidis** [comment] 2016-07-06 07:12
I am far from an expert here, but it appears that your initial point is in a region where Hessian approximation is not positive-definite. Such regions are expected for the non-convex Rastrigin function. This `linesearch` exception breaks things so `try-catch` blocks are needed in real-life cases (meaning cases where not much is guaranteed about the objective function).

What makes `teh/constrained` branch special is that it calls `PositiveFactorizations.jl` to provide a positive-definite Hessian replacement that allows the Newton-style search to continue. This approach by Tim Holy did not appear in the literature AFAIK, but from my own experience it seems to be quite effective (cuts down the number of linesearch exceptions significantly, although not a guaranteed cure and exceptions still happen). Merging this approach into the current `Optim` master would be a major improvement of the constrained search functionality in the package.

**Comment by pkofod** [comment] 2016-07-06 07:43
@multidis That wouldn't really explain why it worked on v0.4.5, would it? Also, we use `PositiveFactorizations.jl` in Newton on master as well, and I think OP is using ConjugateGradient, so that couldn't be it.

I am a bit hesitant to look at your code @Ken-B. You seem to provide it under the MIT license, but is this your own implementation, or a translation from a source of unknown license? I want to do something like this in the future (maybe we should cooperate?), so I don't really want to risk running into the sticky license spider web. Again, if you could give me an example that works on some version of Optim and MinFinder (and Julia) but doesn't work with Optim v0.5, it would be great :) Unfortunately, I missed your package when doing some of the breaking changes, as MinFinder is not in METADATA.jl

**Comment by multidis** [comment] 2016-07-06 07:53
One interesting observation is that when tests for non-convex functions are repeated 100's of times, some runs fail with the linesearch exception on `master` but not on `teh/constrained`. I do not have a closed-form objective function to provide a reproducible example (perhaps this Rastrigin case could be one?), but can definitely say that there must be some other non-positive-definite Hessian differences despite `PositiveFactorizations.jl` called in the Newton code.

Sorry if this is tangential to the current issue, it just resonated with my frequent cases of tests sometimes running into the linesearch exception and sometimes not.

**Comment by pkofod** [comment] 2016-07-06 08:25
Well, there may very well be differences between hz on `master` and `teh/constrained`. However, that can't explain the current issue, because here the difference is between v0.4.5 and v.0.5.0. If you would open another issue with your problem, I would love to look into the differences between hz on master and constrained.

**Comment by Ken-B** [comment] 2016-07-06 10:30
Thanks for all your comments @pkofod and @multidis!

To clarify, I'm running this only on Julia v0.4.5, not on Julia v0.5-:
```jullia
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Yes, the code is MIT licensed. I wrote it from scratch based on the article, not based on any other code (there is indeed code accompanying the article, but I don't know C++). I'm very much open to collaboration, but be aware my optimization experience is limited to this simple package :) 

If you want to look at my code and tests, it's on the `new_optim_api` branch. On that branch all tests pass using Optim v0.4.5 but fail for Optim v0.5.0 because of the Rastrigin test above.

I don't know enough about constrained optimization to comment on the difference between master and teh/constrained with PositiveFactorizations.jl. I only find it interesting that it just works with that branch :)

MinFinder is indeed not in Metadata, that's my fault, I should have registered it much earlier. See also #73. I was in the process of cleaning it up for registration when I noticed this issue from Travis failure. Once tests pass I will register it promptly.

And the depreciation warnings are only from running `using Optim`, the only package`MinFinder` depends on. My package is basically an extension of Optim. [Here are all the warnings](https://gist.github.com/Ken-B/c5b3a9970e33b5c31be98b6919741d4e).

Finally, let me also mention that I reset the seed before each test, not for failing linesearches but because MinFinder is a heuristic and therefore not always finds all the known minima.

Let me now if you have further questions and what I can do to help.
Thank you.

**Comment by pkofod** [comment] 2016-07-06 10:34
Thank you for the explanation and the clarifications. I will see if I can find some time to fix this, so you can continue with your development / registration asap. I can't promise you when it's fixed, though, because I am currently unaware of what is causing the problem.

**Comment by multidis** [comment] 2016-07-21 21:00
May be I am missing something but this example with initial guess at `[0; 0]` returns as non-convergent after 1 iteration, despite the fact that the gradient at the current point is identically zero.

 * Algorithm: Fminbox with Conjugate Gradient
 * Starting Point: [0.0,0.0]
 * Minimizer: [0.0,0.0]
 * Minimum: -2.000000e+00
 * Iterations: 1
 * Convergence: false
   * |x - x'| < 1.0e-32: false
   * |f(x) - f(x')| / |f(x)| < 1.0e-32: false
   * |g(x)| < 1.0e-08: false
   * Reached Maximum Number of Iterations: false
 * Objective Function Calls: 1
 * Gradient Calls: 1

**Comment by anriseth** [comment] 2016-08-13 07:39
@multidis I think your example that starts at a local minimum should be fixed with #262

**Comment by multidis** [comment] 2016-08-13 08:38
@anriseth indeed `converged = false` regardless of the gradient norm before the first step of `cg` and `bfgs` was causing this problem. Thanks for taking care of that!

**Comment by pkofod** [comment] 2016-08-14 07:25
Thanks for the bug report and the fix!

**Closed by pkofod** 2016-08-14 07:25 UTC
